version: "2"
services:
  arango:
    image: arangodb
    volumes:
      - ~/.vtools/data/arango:/var/lib/arangodb3
    ports:
      - "8529:8529"
    environment:
      ARANGO_ROOT_PASSWORD: "Uz2exeiseePhaf"
