version: "2"
services:
  minio:
    image: minio/minio
    volumes:
      - ~/.vtools/data/minio:/data
    ports:
      - "9000:9000"
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
