version: "2"
services:
  postgres:
    image: postgres:11
    ports:
      - 5432:5432
    volumes:
      - ~/.vtools/data/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'password'
